var c1 = document.getElementById("canvas1");
c1.width = window.innerWidth - 66;
c1.height = window.innerHeight - 11;
var w = window.innerWidth - 66;
var h = window.innerHeight - 11;
var canvas1 = c1.getContext("2d");
canvas1.beginPath();
canvas1.moveTo(50, h - 50);
canvas1.lineTo(w - 420, h - 50);
canvas1.lineWidth = 2;
canvas1.strokeStyle = "blue";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(50, h - 50);
canvas1.lineTo(50, 50);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "green";
canvas1.stroke();
//marks y
canvas1.beginPath();
canvas1.moveTo(45, h - 50);
canvas1.lineTo(55, h - 50);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(45, h - 60);
canvas1.lineTo(55, h - 60);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(45, h - 70);
canvas1.lineTo(55, h - 70);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(45, h - 80);
canvas1.lineTo(55, h - 80);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(45, h - 90);
canvas1.lineTo(55, h - 90);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(45, h - 100);
canvas1.lineTo(55, h - 100);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(45, h - 110);
canvas1.lineTo(55, h - 110);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(45, h - 120);
canvas1.lineTo(55, h - 120);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(45, h - 130);
canvas1.lineTo(55, h - 130);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(45, h - 140);
canvas1.lineTo(55, h - 140);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(45, h - 150);
canvas1.lineTo(55, h - 150);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(45, h - 160);
canvas1.lineTo(55, h - 160);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(45, h - 170);
canvas1.lineTo(55, h - 170);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(45, h - 180);
canvas1.lineTo(55, h - 180);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(45, h - 190);
canvas1.lineTo(55, h - 190);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(45, h - 200);
canvas1.lineTo(55, h - 200);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(45, h - 210);
canvas1.lineTo(55, h - 210);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
//marks x
canvas1.beginPath();
canvas1.moveTo(50, h - 55);
canvas1.lineTo(50, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(60, h - 55);
canvas1.lineTo(60, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(70, h - 55);
canvas1.lineTo(70, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(80, h - 55);
canvas1.lineTo(80, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(90, h - 55);
canvas1.lineTo(90, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(100, h - 55);
canvas1.lineTo(100, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(110, h - 55);
canvas1.lineTo(110, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(120, h - 55);
canvas1.lineTo(120, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(130, h - 55);
canvas1.lineTo(130, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(140, h - 55);
canvas1.lineTo(140, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(150, h - 55);
canvas1.lineTo(150, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(160, h - 55);
canvas1.lineTo(160, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(170, h - 55);
canvas1.lineTo(170, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(180, h - 55);
canvas1.lineTo(180, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(190, h - 55);
canvas1.lineTo(190, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(200, h - 55);
canvas1.lineTo(200, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(210, h - 55);
canvas1.lineTo(210, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(220, h - 55);
canvas1.lineTo(220, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(230, h - 55);
canvas1.lineTo(230, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(240, h - 55);
canvas1.lineTo(240, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(250, h - 55);
canvas1.lineTo(250, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(260, h - 55);
canvas1.lineTo(260, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(270, h - 55);
canvas1.lineTo(270, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(280, h - 55);
canvas1.lineTo(280, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(290, h - 55);
canvas1.lineTo(290, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(300, h - 55);
canvas1.lineTo(300, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(310, h - 55);
canvas1.lineTo(310, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(320, h - 55);
canvas1.lineTo(320, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(330, h - 55);
canvas1.lineTo(330, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(340, h - 55);
canvas1.lineTo(340, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(350, h - 55);
canvas1.lineTo(350, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(360, h - 55);
canvas1.lineTo(360, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(370, h - 55);
canvas1.lineTo(370, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(380, h - 55);
canvas1.lineTo(380, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(390, h - 55);
canvas1.lineTo(390, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(400, h - 55);
canvas1.lineTo(400, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(410, h - 55);
canvas1.lineTo(410, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(420, h - 55);
canvas1.lineTo(420, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(430, h - 55);
canvas1.lineTo(430, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(440, h - 55);
canvas1.lineTo(440, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(450, h - 55);
canvas1.lineTo(450, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(460, h - 55);
canvas1.lineTo(460, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(470, h - 55);
canvas1.lineTo(470, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(480, h - 55);
canvas1.lineTo(480, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(490, h - 55);
canvas1.lineTo(490, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(500, h - 55);
canvas1.lineTo(500, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(510, h - 55);
canvas1.lineTo(510, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(520, h - 55);
canvas1.lineTo(520, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(530, h - 55);
canvas1.lineTo(530, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(540, h - 55);
canvas1.lineTo(540, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(550, h - 55);
canvas1.lineTo(550, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(560, h - 55);
canvas1.lineTo(560, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(570, h - 55);
canvas1.lineTo(570, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(580, h - 55);
canvas1.lineTo(580, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(590, h - 55);
canvas1.lineTo(590, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(600, h - 55);
canvas1.lineTo(600, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(610, h - 55);
canvas1.lineTo(610, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(620, h - 55);
canvas1.lineTo(620, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(630, h - 55);
canvas1.lineTo(630, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(640, h - 55);
canvas1.lineTo(640, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(650, h - 55);
canvas1.lineTo(650, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(660, h - 55);
canvas1.lineTo(660, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(670, h - 55);
canvas1.lineTo(670, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(680, h - 55);
canvas1.lineTo(680, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(690, h - 55);
canvas1.lineTo(690, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(700, h - 55);
canvas1.lineTo(700, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(710, h - 55);
canvas1.lineTo(710, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(720, h - 55);
canvas1.lineTo(720, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(730, h - 55);
canvas1.lineTo(730, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(740, h - 55);
canvas1.lineTo(740, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(750, h - 55);
canvas1.lineTo(750, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(760, h - 55);
canvas1.lineTo(760, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(770, h - 55);
canvas1.lineTo(770, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(780, h - 55);
canvas1.lineTo(780, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(790, h - 55);
canvas1.lineTo(790, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(800, h - 55);
canvas1.lineTo(800, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(810, h - 55);
canvas1.lineTo(810, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(820, h - 55);
canvas1.lineTo(820, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(830, h - 55);
canvas1.lineTo(830, h - 45);
canvas1.lineWidth = 1;
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(840, h - 55);
canvas1.lineTo(840, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(850, h - 55);
canvas1.lineTo(850, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(860, h - 55);
canvas1.lineTo(860, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
canvas1.beginPath();
canvas1.moveTo(870, h - 55);
canvas1.lineTo(870, h - 45);
canvas1.lineWidth = 1;
canvas1.strokeStyle = "red";
canvas1.stroke();
var xCoordPE;
var xCoordPS;
var yCoordPE;
var yCoordPS;
var xCoordPSB;
var xCoordPEB;

function xCoordS() {
    xCoordPS = prompt("Lines Starting x");
    xCoordPSB = parseInt(xCoordPS);
    document.getElementById("xCoordBS").innerHTML = xCoordPSB;
    xCoordPSB += 50;
}

function yCoordS() {
    yCoordPS = prompt("Lines Starting y");
    document.getElementById("yCoordBS").innerHTML = yCoordPS;
}

function xCoordE() {
    xCoordPE = prompt("Lines Ending x");
    xCoordPEB = parseInt(xCoordPE);
    document.getElementById("xCoordBE").innerHTML = xCoordPEB;
}

function yCoordE() {
    yCoordPE = prompt("Lines Ending y");
    document.getElementById("yCoordBE").innerHTML = yCoordPE;
    xCoordPEB += 50;
}
var lineColor;

function color() {
    var cChoice = prompt("What color do you want your line to be");
    if (cChoice == "red") {
        lineColor = "red";
    }
    if (cChoice == "orange") {
        lineColor = "orange";
    }
    if (cChoice == "yellow") {
        lineColor = "yellow";
    }
    if (cChoice == "green") {
        lineColor = "green";
    }
    if (cChoice == "blue") {
        lineColor = "blue";
    }
    if (cChoice == "indigo") {
        lineColor = "indigo";
    }
    if (cChoice == "violet") {
        lineColor = "orange";
    }
    document.getElementById("colorB").innerHTML = lineColor;
}

function draw() {
    var c1 = document.getElementById("canvas1");
    var canvas1 = c1.getContext("2d");
    canvas1.beginPath();
    canvas1.moveTo(xCoordPSB, h - yCoordPS - 50);
    canvas1.lineTo(xCoordPEB, h - yCoordPE - 50);
    canvas1.strokeStyle = lineColor;
    canvas1.lineWidth = 1;
    canvas1.stroke();
}